# -*- coding: utf-8 -*-
"""LAB SHEET flicker 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uCmAv_XaMKYj6pmvdlefB1id-qmA951H
"""

import pandas as pd
 import numpy as np
 from functools import reduce

# prompt: df = pd.read_CSV("/content/drive/MyDrive/BL-Flickr-Images-Book.csv") print(df.head()) auto corret

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/BL-Flickr-Images-Book.csv")
print(df.head())

for col in df.columns:
  print(col)

to_drop=["Shelfmarks","Place of Publication","Title","Corporate Author","Engraver",
         "Former owner"]
df.drop(to_drop,inplace=True,axis=1)
df.head()

df.set_index("Identifier",inplace=True)
df.head()

unwanted_characters=['[',',','-']

def clean_dates(item):
  dop=str(item.loc['Date of Publication'])

  if dop=='nan' or dop[0]=='[':
    return np.NaN

  for character in unwanted_characters:
    if character in dop:
      character_index=dop.find(character)
      dop=dop[:character_index]
  return dop

df['Date of Publication']=df.apply(clean_dates,axis=1)

df['Date of Publication'].head()

def clean_title(title):
  if title=='nan':
    return 'NaN'
  if title[0]=='[':
    title=title[1:title.find(']')]
  if 'by'in title:
    title =title[:title.find('by')]
  elif 'By'in title:
      title=title[:title.find('By')]
  if'[' in title:
    title=title[:title.find('[')]
    title=title[:-2]
    df['title']=df['title'].apply(clean_title)
    df.head()

df.loc[4159587]
df.head(20)